apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHJvb3Q= #rootroot
  MYSQL_USER: dGVzdHVzZXI= #testuser
  MYSQL_PASSWORD: cGFzc3dvcmQ= #password